### PR TITLE
Add sticky session support

### PR DESCRIPTION
**Pull request by ArthurHlt**
In accordance to this [http://www.iamjambay.com/2013/10/a-quick-tour-of-cloud-foundry-router.html](http://www.iamjambay.com/2013/10/a-quick-tour-of-cloud-foundry-router.html) i think it's better idea to change `PHPSESSID` by `JSESSIONID` . It will permit to never loose session in multi-instance php website.
Don't you think?

### CODE REVIEW

**Comment by squeedee** [comment]
I've created a story for this: https://www.pivotaltracker.com/story/show/75635218
We will look at it shortly. Thanks :D

**Comment by ArthurHlt** [comment]
Great !
Sorry i made a pull request on master branch you're being polluted by my commits, anyway just change `session.name = PHPSESSID` by `session.name = JSESSIONID` in `conf/php/php.ini`.

**Comment by squeedee** [comment]
Yeah I was going to mention to you, you have some travis credentials etc in here. I'm going to close this PR to stop the ticket updating. We'll add this to our next release (1.0.2)

**Comment by ArthurHlt** [comment]
don't worry for travis, it's encrypted

**Comment by squeedee** [comment]
We patched this here: https://github.com/cloudfoundry/php-buildpack/commit/875c410c879ce37f43a5aad3e00623d02bca83c1

Thanks for the PR!

**Pull request closed without merging**
